language: python

cache: pip

python:
  - "3.6"

env:
  - PYTORCH_PACKAGE=pytorch-cpu

stages:
  - Lint Check
  - Test

jobs:
  include:
    - stage: Lint Check
      python: "3.6"
      before_install: # nothing to do
      install: pip install flake8
      script: flake8 torchgan/
      after_success: # nothing to do

    - stage: Test
      before_install:
        - sudo apt-get update
        - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
        - bash miniconda.sh -b -p $HOME/miniconda
        - export PATH="$HOME/miniconda/bin:$PATH"
        - hash -r
        - conda config --set always_yes yes --set changeps1 no
        - conda update -q conda
        # Useful for debugging any issues with conda
        - conda info -a
        - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION
        - source activate test-environment
        - conda install pytorch torchvision cpuonly -c pytorch
      install:
        - python setup.py install
        - pip install --upgrade pytest pytest-cov coverage scipy

      script:
        - py.test --cov torchgan --cov-report term-missing

      after_success:
        - bash <(curl -s https://codecov.io/bash)
        - source deactivate
