language: python
python:
  - "3.6" # Enough to test on 1 version. We are anyways installing version 3.7 on travis before
          # testing

# command to install dependencies
install:
  - sudo apt-get update
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a

  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION pytorch scipy -c pytorch
  - source activate test-environment
  - python setup.py install
  - pip install --upgrade pytest pytest-cov
  - pip install flake8

# command to run tests
script:
  - pytest --cov=./
  - flake8 torchgan/

# command for coverage results
after_success:
  - bash <(curl -s https://codecov.io/bash)
